export const ARABIC_LANGUAGE_ISO_CODE = 'ar';
export const ENGLISH_LANGUAGE_ISO_CODE = 'en';
export const SUPPORTED_LANGUAGES_ISO_CODES = [
  ARABIC_LANGUAGE_ISO_CODE,
  ENGLISH_LANGUAGE_ISO_CODE,
];

export const GROUP_NOTIFICATION_TYPE = 'GROUP';
export const PERSONALIZED_NOTIFICATION_TYPE = 'PERSONALIZED';
export const NOTIFICATIONS_TYPES = [
  GROUP_NOTIFICATION_TYPE,
  PERSONALIZED_NOTIFICATION_TYPE,
];

export const PUSH_NOTIFICATION_PROVIDER = 'PUSH';
export const SMS_NOTIFICATION_PROVIDER = 'SMS';
export const NOTIFICATIONS_PROVIDERS = [
  PUSH_NOTIFICATION_PROVIDER,
  SMS_NOTIFICATION_PROVIDER,
];

export const DIRECT_NOTIFICATION_JOB_TYPE = 'DIRECT';
export const CHILD_NOTIFICATION_JOB_TYPE = 'CHILD';
export const NOTIFICATIONS_JOB_TYPES = [
  DIRECT_NOTIFICATION_JOB_TYPE,
  CHILD_NOTIFICATION_JOB_TYPE,
];

export const CREATED_NOTIFICATION_STATUS = 'CREATED';
export const ENQUEUED_NOTIFICATION_STATUS = 'ENQUEUED';
export const PROCESSED_NOTIFICATION_STATUS = 'PROCESSED';
export const DELIVERED_NOTIFICATION_STATUS = 'DELIVERED';
export const FAILED_NOTIFICATION_STATUS = 'FAILED';
export const NOTIFICATIONS_STATUSES = [
  CREATED_NOTIFICATION_STATUS,
  ENQUEUED_NOTIFICATION_STATUS,
  PROCESSED_NOTIFICATION_STATUS,
  DELIVERED_NOTIFICATION_STATUS,
  FAILED_NOTIFICATION_STATUS,
];
