name: ci

on:
  push:
    branches: [ master ]

jobs:
  api-server:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api-server/
          push: true
          tags: mohllal/nf-be-challenge-api-server:latest,mohllal/nf-be-challenge-api-server:${{ steps.slug.outputs.sha7 }}
  notifications-forwarder:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./notifications-forwarder/
          push: true
          tags: mohllal/nf-be-challenge-notifications-forwarder:latest,mohllal/nf-be-challenge-notifications-forwarder:${{ steps.slug.outputs.sha7 }}
  notifications-processor:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./notifications-processor/
          push: true
          tags: mohllal/nf-be-challenge-notifications-processor:latest,mohllal/nf-be-challenge-notifications-processor:${{ steps.slug.outputs.sha7 }}


